#!/bin/sh
set -e

# Use env vars with defaults
: "${MLFLOW_DB:=mlflow_db}"
: "${FASTAPI_DB:=fastapi_db}"
: "${AIRFLOW_DB:=airflow_db}"
: "${LANGCHAIN_DB:=langchain_db}"
: "${DBT_DB:=dbt_db}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $MLFLOW_DB;
    CREATE DATABASE $FASTAPI_DB;
    CREATE DATABASE $AIRFLOW_DB;
    CREATE DATABASE $LANGCHAIN_DB;
    CREATE DATABASE $DBT_DB;

    GRANT ALL PRIVILEGES ON DATABASE $MLFLOW_DB TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE $FASTAPI_DB TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE $AIRFLOW_DB TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE $LANGCHAIN_DB TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE $DBT_DB TO $POSTGRES_USER;
EOSQL
